### ISSUE TITLE
Walkabout Not Showing Button in Space Center

### ISSUE THREAD

**Issue by PadroneSF** [linuxgurugamer/WalkAbout#1]
KSP 1.9.1 64 Bit w/ all DLC

Problem:  Walkabout doesn't have a button on the Space Center screen.

Mods Installed:

- ClickThroughBlocker
- Toolbar
- ToobarControl
- Walkabout

Reproduction Steps:

- Start KSP
- Enter game

Result: No button on either Stock or Blizzy toolbars, nothing to add inside Toolbar.  (Screenshot in dropbox)

Note:  Toolbar installed since the Walkabout Github page indicates the activation keys were removed in favor of buttons.

Exited game.  Removed Toolbar mod and dependencies, leaving Squad, Squad expansion  and Walkabout directories in Gamedata.  (Just in case it's an  issue with the Toolbar.)

Re-entered game.

Result: Still no toolbar indications of mods at bottom right of screen.

[Logs and such:](https://www.dropbox.com/sh/mhku4vkltd1fdg3/AAAv28aqZWm0yfMEW2p07dlRa?dl=0)

https://www.dropbox.com/sh/mhku4vkltd1fdg3/AAAv28aqZWm0yfMEW2p07dlRa?dl=0

**Comment by linuxgurugamer** [comment]
You don't have the right version of WalkAbout installed.
My version IS A BETA.  Says so right in the title:

> [1.8.x, 1.9.x] WalkAbout BETA

And to install, it is NOT yet available in CKAN.  Again, it says in the OP where it is available from:

> Availability
> 
> Source: https://github.com/linuxgurugamer/WalkAbout
> Download: https://github.com/linuxgurugamer/WalkAbout/releases - BETA
> License: GPL

Finally, since this IS a beta, you should post your messages where the BETA is being discussed.  Not here.

I'm closing this since you have the wrong version installed.  How do I know?  It says so right in the log file.
Your log file has:

> WalkAbout v1.0.0.0

while it should say something like:

> WalkAbout v0.1.8.0 / v1.7.1

**Comment by PadroneSF** [comment]
Sorry for making a mistake and wasting your time. When I saw that the forum title said "[1.8.x, 1.9.x] WalkAbout BETA" I thought the beta would be for 1.9.x.

Heaven knows you're busy enough. Thank you for all the mods you're keeping alive!

----- Original message -----
